[project]
name = "faster-whisper-api-oci"
version = "0.1.0"
description = "a Flask API for Faster Whisper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "flask>=3.1.2",
    "mutagen>=1.47.0",
    "python-dotenv>=1.2.1",
    "bcrypt>=4.0.0",
]
